### PR TITLE
Dynamic/Random Background Images Working

### PR DESCRIPTION
**Pull request by LaTonia-Mertica**
on landing page @Jason-Doze 🤓 

Also, completed a few other things from my todo items list, which I'll get back to after this PR is approved. So psyched!!!!!

### CODE REVIEW

**Comment by LaTonia-Mertica** [comment]
Hello Again @Jason-Doze,

Hopefully exciting stuff awaiting in this/these commit(s). Basically, I completed the list of todos we generated at our last meet and ... - such as allowing users to see their uploaded img in a more prominent way on both the add/edit pages. You'll see I played with colors et cetera to get stuff to stand out but we can settle colors for final. Also, the uid (above the description on the landing page), the browse, and delete/reset buttons are not yet wired. 

I'm double checking issues to add/edit as needed. Hope holiday Monday has been kind to you. See you soon🤓

**Comment by LaTonia-Mertica** [comment]
Apologies - forgot to add that my next sweep will be to review the code you included for enhanced styles and incorporate throughout the site was able ... looking forward to doing this just didn't have bandwidth to get to it in this round ... talk soon🤪🤗🎯

**Review by Jason-Doze — COMMENTED** [review]
Apologies @LaTonia-Mertica, I had no notifications on my email banner...just opened up my email and had tons of unread messages. I'll pull it now and have a gander!

**Review by Jason-Doze — APPROVED** [review]

**Comment by LaTonia-Mertica** [comment]
No worries🤓
*___________________________________________*
*La'Tonia Mertica*
(Luh Tone Yuh Merr Treece)
*Founder & Executive Officer*

La'Tonia Mertica 'Communications & Creatives Specialist'
<https://mailchi.mp/50361129f72d/latoniamertica>

2200 South Salina Street #684
Syracuse, New York 13205
***@***.***
digital portfolio gateway: latoniamertica.dev <http://latoniamertica.dev>

**Pull request merged**
